module.exports = {

  ORDER_CREATED:
    'ORDER_CREATED',

  WORK_ORDER_CREATED:
    'WORK_ORDER_CREATED',

  WORK_ORDER_UPDATED:
    'WORK_ORDER_UPDATED',

  LOT_CREATED:
    'LOT_CREATED',

  LOT_UPDATED:
    'LOT_UPDATED',

  MATERIAL_CREATED:
    'MATERIAL_CREATED',

  MATERIAL_UPDATED:
    'MATERIAL_UPDATED',

  INCIDENT_CREATED:
    'INCIDENT_CREATED',

  INCIDENT_RESOLVED:
    'INCIDENT_RESOLVED',

  MATERIAL_REQUESTED:
    'MATERIAL_REQUESTED',

  RESERVATION_UPDATED:
    'RESERVATION_UPDATED',

  RESERVATION_MESSAGE:
    'RESERVATION_MESSAGE',

  LOT_COMPLETED:
    'LOT_COMPLETED'

}