services:
  postgres:
    image: postgres:17-alpine
    container_name: erp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aeronexis_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aeronexis-network

  mongodb:
    image: mongo:6
    container_name: erp-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - aeronexis-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: erp-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - aeronexis-network

  redis:
    image: redis:7-alpine
    container_name: erp-redis
    ports:
      - "6379:6379"
    networks:
      - aeronexis-network

# Déclaration des volumes gérés par Docker Compose
volumes:
  pgdata:      # <-- Notez que "external: true" a disparu
  mongodata:

networks:
  aeronexis-network:
    driver: bridge